// Mocks generated by Mockito 5.4.4 from annotations
// in checklist/test/features/configurations/controllers/configurations_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:checklist/app/features/configurations/dao/interface/configurations_dao.dart'
    as _i3;
import 'package:checklist/app/features/configurations/models/configurations.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeConfigurations_0 extends _i1.SmartFake
    implements _i2.Configurations {
  _FakeConfigurations_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ConfigurationsDAO].
///
/// See the documentation for Mockito's code generation for more information.
class MockConfigurationsDAO extends _i1.Mock implements _i3.ConfigurationsDAO {
  @override
  _i4.Future<int> updateConfigs(_i2.Configurations? configurations) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateConfigs,
          [configurations],
        ),
        returnValue: _i4.Future<int>.value(0),
        returnValueForMissingStub: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<_i2.Configurations> getConfig() => (super.noSuchMethod(
        Invocation.method(
          #getConfig,
          [],
        ),
        returnValue: _i4.Future<_i2.Configurations>.value(_FakeConfigurations_0(
          this,
          Invocation.method(
            #getConfig,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Configurations>.value(_FakeConfigurations_0(
          this,
          Invocation.method(
            #getConfig,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Configurations>);
}
